name: Pythonseer build and publish via tag

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
    build-n-publish:
      runs-on: ubuntu-latest
      permissions:
        contents: write
      steps:
      - name: "✔️ Checkout"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: "✏️ Generate release changelog"
        uses: BobAnkh/auto-generate-changelog@v1.2.5
        with:
          ACCESS_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          generateReleaseNotes: true
      - name: "🛠 Install and publish with poetry"
        run: |
            make setup
            poetry config pypi-token.pypi "${{ secrets.PYPI_API_TOKEN }}"
            poetry publish --build
      - name: "🤖 Announce on lemmy.dbzer0.com"
        run: |
            python -m pip install pythorhead
            python .github/workflows/publish_on_lemmy.py ${{ env.RELEASE_VERSION }}
        env:
          LEMMY_BOT_PASSWORD: ${{ secrets.LEMMY_BOT_PASSWORD }}
